version: '3.7'

services:

  postgres:
      environment:
        - POSTGRES_DB=mcedev

  app:
    build:
      context: .
      image: mce-django-server:latest
      environment:
        - DJANGO_SETTINGS_MODULE=mce_django_server.settings.dev
        - DATABASE_URL=psql://mce:password@postgres/mcedev
        - DEBUG=true
        - LOG_LEVEL=DEBUG
      volumes:
        - .:/code:ro
      ports:
        - 8000:8000

  worker:
      image: mce-django-server:latest
      environment:
        - DJANGO_SETTINGS_MODULE=mce_django_server.settings.dev
        - DATABASE_URL=psql://mce:password@postgres/mcedev
        - DEBUG=true
        - LOG_LEVEL=DEBUG
      volumes:
        - .:/code:ro

