version: '3.7'

services:

  traefik:
    image: "traefik:1.7-alpine"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - ./traefik/traefik.toml:/traefik.toml:ro
      - ./traefik/acme.json:/acme.json
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    depends_on:
      - app
      - flower


