version: '3.7'

volumes:
  postgres_data:
      driver: local
  redis_data:
      driver: local
  common_data:
      driver: local

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24

services:

  postgres:
    image: postgres:12-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=mce
      - POSTGRES_USER=mce
      - POSTGRES_PASSWORD=password
    #ports:
    #  - 5432:5432

  redis:
    image: redis:5-alpine
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

  app:
    environment: &global_env
      - CACHE_URL=rediscache://redis:6379/0?client_class=django_redis.client.DefaultClient
      - DATABASE_URL=psql://mce:password@postgres/mce
      - DJANGO_SETTINGS_MODULE=mce_django_server.settings.prod
      - DEBUG=false
      - LOG_LEVEL=INFO
      - TZ=Europe/Paris
    command: bash -c "./manage.py check && ./manage.py migrate && gunicorn --workers 1 -k gevent --bind 0.0.0.0:8000 mce_django_server.wsgi:application"
    links:
      - redis
      - postgres
    #labels:
    #  - traefik.enable=true
    #  - traefik.backend=app
    #  - traefik.frontend.rule=Host:demo.multi-cloud-explorer.org
    #  - traefik.port=8000

  worker:
    environment: *global_env
    command: bash -c "./manage.py qcluster"
    volumes:
      - common_data:/shared
    links:
      - redis
      - postgres
    depends_on:
      - app



